export const PATIENT_LIST = "PATIENT_LIST";
export const PATIENT_LIST_SUCCESS = "PATIENT_LIST_SUCCESS";
export const PATIENT_LIST_FAILED = "PATIENT_LIST_FAILED";

export const PATIENT_SAVE = "PATIENT_SAVE";
export const PATIENT_SAVE_SUCCESS = "PATIENT_SAVE_SUCCESS";
export const PATIENT_SAVE_FAILED = "PATIENT_SAVE_FAILED";

export const PATIENT_DETAIL = "PATIENT_DETAIL";
export const PATIENT_DETAIL_SUCCESS = "PATIENT_DETAIL_SUCCESS";
export const PATIENT_DETAIL_FAILED = "PATIENT_DETAIL_FAILED";

export const PATIENT_DELETE = "PATIENT_DELETE";
export const PATIENT_DELETE_SUCCESS = "PATIENT_DELETE_SUCCESS";
export const PATIENT_DELETE_FAILED = "PATIENT_DELETE_FAILED";

export const PATIENT_REDIRECT = "PATIENT_REDIRECT";







